/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyktx.view.DangKy;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import quanlyktx.DAO.DAO;
import quanlyktx.model.TaiKhoan;
import quanlyktx.view.Admin.AdminView;
import quanlyktx.view.DangNhap.DangNhapView;
import quanlyktx.view.User.SinhVienView;

/**
 *
 * @author luong
 */
public class DangKyView extends javax.swing.JFrame {

    /**
     * Creates new form DangKyView
     */
    public DangKyView() {
        setIcon();
        initComponents();
        ImageIcon A = new ImageIcon(getClass().getResource("hide.png"));
        show_hide_pass.setIcon(A);
        
        controller = new DAO();
    }
    
    public boolean checkEmpty(String key, String notify) {
        if (key.trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }
    
    public boolean checkTaiKhoan(String taiKhoan, String notify)
    {
        String pattUname = "^[Nn]+[\\d]{2}+[A-Za-z]{4}+[\\d]{3}$";
        if(!taiKhoan.trim().matches(pattUname))
        {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }
    
    public boolean checkEmail(String email, String notify)
    {
        String pattEmail = "^[Nn]+[\\d]{2}+[A-Za-z]{4}+[\\d]{3}+@student.ptithcm.edu.vn$";
        if(!email.trim().matches(pattEmail))
        {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }
    
    public boolean checkPwrd(String pwrd, String notify)
    {
        String pattPwrd = "^.[\\w\\S]{5,}$";
        if(!pwrd.trim().matches(pattPwrd))
        {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }
    
    public boolean CheckCorrect(String username, String email, String password) {
        String pattUname = "^[Nn]+[\\d]{2}+[A-Za-z]{4}+[\\d]{3}$";
        String pattEmail = "^[Nn]+[\\d]{2}+[A-Za-z]{4}+[\\d]{3}+@student.ptithcm.edu.vn$";
        String pattPwrd = "^.[\\w\\S]{5,}$";
        
        boolean ret;
        
        if(username.trim().matches(pattUname)
                && email.trim().matches(pattEmail)
                && password.trim().matches(pattPwrd))
        {
            ret = true;
        }
        else
        {
            ret = false;
        }
        return ret;
    }
    
    private void kiemTraNhap()
    {
        try {
            
            String username = txtTaiKhoan.getText().toLowerCase();
            String email = txtEmail.getText().toLowerCase();
            String password = String.valueOf(txtPassWord.getPassword());

            if(checkEmpty(username, "Nhập tên tài khoản!") && checkTaiKhoan(username, "Tài khoản bắt buộc phải là mã sinh viên!")
                    && checkEmpty(email, "Nhập email!") && checkEmail(email, "Hãy sử dụng email đã cấp của học viện!")
                    && checkEmpty(password, "Nhập password!") && checkPwrd(password, "Mật khẩu phải trên 6 ký tự hoặc hơn!"))
            {
                TaiKhoan taiKhoan = new TaiKhoan(username, password, email, 1);
//                    System.out.println(username + " | " + email + " | " + password);
//                    String name = taiKhoan.getTenTK();
//                    String mail = taiKhoan.getEmail();
//                    String pass = taiKhoan.getMatKhau();
//                    System.out.println(name + " | " + mail + " | " + pass);

                if(controller.addAccountStudent(taiKhoan))
                {
                    JOptionPane.showMessageDialog(rootPane, "Đăng kí tài khoản thành công!");
                    System.out.println("Register success, back to Login Form...");
                    new DangNhapView().setVisible(true);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Đăng ký thất bại!");
                }
            }

        } catch (Exception e) {
            Logger.getLogger(DangKyView.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTaiKhoan = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        show_hide_pass = new javax.swing.JLabel();
        btn_DangKy = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTaiKhoan.setBorder(null);
        txtTaiKhoan.setOpaque(false);
        getContentPane().add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 246, 320, 30));

        txtPassWord.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPassWord.setBorder(null);
        txtPassWord.setOpaque(false);
        getContentPane().add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 345, 300, 30));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 296, 320, 30));

        show_hide_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_hide_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/view/DangKy/hide.png"))); // NOI18N
        show_hide_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_hide_passMouseClicked(evt);
            }
        });
        getContentPane().add(show_hide_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 20, 30));

        btn_DangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DangKyMouseClicked(evt);
            }
        });
        getContentPane().add(btn_DangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 416, 200, 46));

        btn_DangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DangNhapMouseClicked(evt);
            }
        });
        getContentPane().add(btn_DangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 503, 80, 20));

        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/close.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 10, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/DangKiTaiKhoan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean flag = true;
    private void show_hide_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_hide_passMouseClicked
        if (flag) {
            ImageIcon A = new ImageIcon(getClass().getResource("show.png"));
            show_hide_pass.setIcon(A);
            txtPassWord.setEchoChar((char) 0);
            flag = false;
        } else {
            ImageIcon A = new ImageIcon(getClass().getResource("hide.png"));
            show_hide_pass.setIcon(A);
            txtPassWord.setEchoChar((char) 8226);
            flag = true;
        }
    }//GEN-LAST:event_show_hide_passMouseClicked

    private void btn_DangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DangKyMouseClicked
//        this.dispose();
//        new DangNhapView().setVisible(true);
        kiemTraNhap();
    }//GEN-LAST:event_btn_DangKyMouseClicked

    private void btn_DangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DangNhapMouseClicked
        this.dispose();
        new DangNhapView().setVisible(true);
    }//GEN-LAST:event_btn_DangNhapMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0; i <= 1; i += 0.5) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyView().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    
    private DAO controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_DangKy;
    private javax.swing.JLabel btn_DangNhap;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel show_hide_pass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
