/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyktx.view.Admin;

import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import quanlyktx.DAO.DAO;
import quanlyktx.model.Day;
import quanlyktx.model.HopDong;
import quanlyktx.model.LoaiPhong;
import quanlyktx.model.Phong;
import quanlyktx.view.DangNhap.DangNhapView;
import quanlyktx.view.User.SinhVienView;
import quanlyktx.model.SinhVien;
import quanlyktx.model.TaiKhoan;
import quanlyktx.model.ThanNhan;

/**
 *
 * @author luong
 */
public class DangKyKTX extends javax.swing.JFrame {

    private DAO controller;

    static String user = "SV";
    private int giaTien = 0;
    List<Phong> rooms;
    List<Day> ranges;
    List<SinhVien> students;
    List<HopDong> contracts;

    /**
     * Creates new form DangKyKTX
     */
    public DangKyKTX(String id) {
        user = id.trim();
        setIcon();
        initComponents();
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        jRadioButtonNam.setSelected(true);
        cb_phong.setEnabled(false);
        cb_loai_phong.setEnabled(true);
        
        txtSoDienThoai.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
        txtSoDienThoaiNguoiThan.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

        //rooms = controller.getListRoom();
        //ranges = controller.getListRange();
        ImageIcon A = new ImageIcon(getClass().getResource("DangKyKTX.jpg"));
        bg_dang_ky.setIcon(A);

        /////////////////////
        controller = new DAO();
        contracts = controller.getListHopDong();
    }

    public DangKyKTX() {
        setIcon();
        initComponents();
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        jRadioButtonNam.setSelected(true);
        cb_phong.setEnabled(false);
        cb_loai_phong.setEnabled(true);

        //rooms = controller.getListRoom();
        //ranges = controller.getListRange();
        ImageIcon A = new ImageIcon(getClass().getResource("DangKyKTX.jpg"));
        bg_dang_ky.setIcon(A);

        /////////////////////
        controller = new DAO();
        contracts = controller.getListHopDong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dang_ki = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtHovaTen = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtSoDienThoaiNguoiThan = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtTenNguoiThan = new javax.swing.JTextField();
        txtDiaChiNguoThan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtNgayThangNamSinh = new javax.swing.JTextField();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        cb_day = new javax.swing.JComboBox<>();
        cb_phong = new javax.swing.JComboBox<>();
        cb_loai_phong = new javax.swing.JComboBox<>();
        btn_logout = new javax.swing.JLabel();
        btn_help = new javax.swing.JLabel();
        btn_user = new javax.swing.JLabel();
        btn_setting2 = new javax.swing.JLabel();
        setting_view = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        bg_dang_ky = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dang_ki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dang_ki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dang_kiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dang_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, 40));

        txtMaSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMaSV.setBorder(null);
        getContentPane().add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 115, 170, 25));

        txtSoDienThoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSoDienThoai.setBorder(null);
        getContentPane().add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 185, 220, 25));

        txtHovaTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtHovaTen.setBorder(null);
        getContentPane().add(txtHovaTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, 25));

        txtLop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLop.setBorder(null);
        getContentPane().add(txtLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 220, 25));

        txtSoDienThoaiNguoiThan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSoDienThoaiNguoiThan.setBorder(null);
        getContentPane().add(txtSoDienThoaiNguoiThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 315, 220, 25));

        txtGiaTien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGiaTien.setForeground(new java.awt.Color(0, 0, 255));
        txtGiaTien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGiaTien.setBorder(null);
        getContentPane().add(txtGiaTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 445, 370, 25));

        txtQueQuan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQueQuan.setBorder(null);
        getContentPane().add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 220, 25));

        txtTenNguoiThan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenNguoiThan.setBorder(null);
        txtTenNguoiThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNguoiThanActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenNguoiThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 245, 260, 25));

        txtDiaChiNguoThan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDiaChiNguoThan.setBorder(null);
        getContentPane().add(txtDiaChiNguoThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 480, 25));

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDiaChi.setBorder(null);
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 185, 230, 25));

        txtNgayThangNamSinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNgayThangNamSinh.setBorder(null);
        getContentPane().add(txtNgayThangNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 115, 130, 25));

        jRadioButtonNam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.setBorder(null);
        jRadioButtonNam.setOpaque(false);
        jRadioButtonNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonNamMouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButtonNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jRadioButtonNu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonNu.setText("Nữ");
        jRadioButtonNu.setBorder(null);
        jRadioButtonNu.setOpaque(false);
        jRadioButtonNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonNuMouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButtonNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        cb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "I", "J", "H", "Q", "M", "N", "K", "P", " " }));
        cb_day.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_day.setOpaque(false);
        cb_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dayActionPerformed(evt);
            }
        });
        getContentPane().add(cb_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 80, 30));

        cb_phong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        cb_phong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_phong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_phong.setOpaque(false);
        cb_phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_phongActionPerformed(evt);
            }
        });
        getContentPane().add(cb_phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 80, 30));

        cb_loai_phong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ( dịch vụ 1 )", "2 ( dịch vụ 2 )", "3 ( thường )", "", "" }));
        cb_loai_phong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_loai_phong.setOpaque(false);
        getContentPane().add(cb_loai_phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 110, -1));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 190, 55));

        btn_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_helpMouseClicked(evt);
            }
        });
        getContentPane().add(btn_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 190, 55));

        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
        });
        getContentPane().add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 55));

        btn_setting2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setting2MouseClicked(evt);
            }
        });
        getContentPane().add(btn_setting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 495, 190, 55));

        setting_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/setting.jpg"))); // NOI18N
        getContentPane().add(setting_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 191, 220));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/close.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        bg_dang_ky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/DangKyKTX.jpg"))); // NOI18N
        bg_dang_ky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bg_dang_kyMouseClicked(evt);
            }
        });
        getContentPane().add(bg_dang_ky, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        this.dispose();
        new AdminView().setVisible(true);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0; i <= 1; i += 0.2) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened
    private boolean flag = true;
    private void btn_setting2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setting2MouseClicked
        if (flag) {
            setting_view.setVisible(true);
            btn_user.setVisible(true);
            btn_help.setVisible(true);
            btn_logout.setVisible(true);
            flag = false;
        } else {
            setting_view.setVisible(false);
            btn_user.setVisible(false);
            btn_help.setVisible(false);
            btn_logout.setVisible(false);
            flag = true;
        }
    }//GEN-LAST:event_btn_setting2MouseClicked

    private void bg_dang_kyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_dang_kyMouseClicked
        setting_view.setVisible(false);
        flag = true;
        //System.out.println("click dang ky");
    }//GEN-LAST:event_bg_dang_kyMouseClicked

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click user");
        this.dispose();
        new UserView().setVisible(true);
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_helpMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click help");
        new HelpView().setVisible(true);
    }//GEN-LAST:event_btn_helpMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click logout");
        this.dispose();

        new DangNhapView().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void cb_phongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_phongActionPerformed
        cb_loai_phong.setEnabled(true);

        if (cb_phong.getSelectedItem() != null) {
            String phong = cb_phong.getSelectedItem().toString().trim();
            for (Phong room : rooms) {
                if (phong.equals(room.getMaPhong().trim())) {
                    LoaiPhong loaiPhong = controller.getCategoryRoomByIDCategoryRoom(room.getMaLoaiPhong().trim());
                    cb_loai_phong.removeAllItems();
                    cb_loai_phong.addItem(loaiPhong.getTenLoaiPhong());
                    cb_loai_phong.setEditable(false);
                    DecimalFormat formatter = new DecimalFormat("###,###,###");
                    String gia = formatter.format(loaiPhong.getGiaTien()) + "đ x 5 tháng = " + formatter.format(loaiPhong.getGiaTien() * 5) + "đ";
                    giaTien = loaiPhong.getGiaTien() * 5;
                    txtGiaTien.setText(gia);
                }
            }
        }
    }//GEN-LAST:event_cb_phongActionPerformed

    private void btn_dang_kiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dang_kiMouseClicked

        String stringDate = txtNgayThangNamSinh.getText();
        try {
            String gioiTinh = jRadioButtonNam.isSelected() ? "Nam" : "Nữ";
            String day = cb_day.getSelectedItem().toString();
            if (checkEmpty(txtHovaTen.getText(), "Họ và tên?")
                    && checkEmpty(txtMaSV.getText(), "Mã số sinh viên?")
                    && checkExit(txtMaSV.getText().trim().toUpperCase())
                    && checkEmpty(stringDate, "Ngày sinh?") && checkBirthday(stringDate, "Không đúng định dạng ngày!")
                    && checkEmpty(txtLop.getText(), "Lớp ?")
                    && checkEmpty(txtQueQuan.getText(), "Quê quán ?")
                    && checkEmpty(txtSoDienThoai.getText(), "Số điện thoại?")
                    && checkSoDienThoai(txtSoDienThoai.getText())
                    && checkEmpty(txtDiaChi.getText(), "Địa chỉ?")
                    && checkEmpty(txtTenNguoiThan.getText(), "Tên người thân?")
                    && checkEmpty(txtDiaChiNguoThan.getText(), "Địa chỉ người thân?")
                    && checkEmpty(txtSoDienThoaiNguoiThan.getText(), "Số điện thoại người thân ?")
                    && checkComboBox(day, "Vui lòng chọn dãy và phòng!")) {

                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date ngaySinh = format.parse(stringDate);

                Date currentDate = java.util.Calendar.getInstance().getTime();// lấy ngày hiện tại
                Date paymentTerm = addDays(currentDate, 14); // thời hạn trả là 14 ngày
                Date endDate = addMonths(currentDate, 5);

                int contractNumber = contracts.size();// số lượng hợp đồng
                String idHopDong = "HD" + ++contractNumber;

                SinhVien sinhVien
                        = new SinhVien(
                                txtMaSV.getText().toUpperCase().trim(),
                                txtHovaTen.getText(),
                                ngaySinh,
                                gioiTinh,
                                txtQueQuan.getText(),
                                txtSoDienThoai.getText(),
                                txtDiaChi.getText(),
                                txtMaSV.getText());

                TaiKhoan taiKhoan = new TaiKhoan(
                        txtMaSV.getText().toUpperCase().trim(),
                        "123",
                        "",
                        1);

                ThanNhan tn = new ThanNhan(
                        txtMaSV.getText(),
                        txtTenNguoiThan.getText(),
                        txtDiaChiNguoThan.getText(),
                        txtSoDienThoaiNguoiThan.getText());

                HopDong hd = new HopDong(
                        idHopDong,
                        user.trim(),
                        txtMaSV.getText().toUpperCase().trim(),
                        cb_phong.getSelectedItem().toString(),
                        giaTien,
                        paymentTerm,
                        1,
                        currentDate,
                        endDate,
                        null);
                System.out.println(user.trim());
                if (controller.addAccountStudent(taiKhoan)) {
                    if (controller.addStudent(sinhVien)) {
                        if (controller.addFamily(tn)) {
                            if (controller.addHopDong(hd)) {
                                JOptionPane.showMessageDialog(rootPane, "Đăng kí thành công!");
                            }
                            new QuanLySVView(user.trim()).setVisible(true);
                            this.dispose();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Đăng kí thất bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đăng kí tài khoản thành công!");
                }
            }

        } catch (ParseException ex) {
            Logger.getLogger(DangKyKTX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dang_kiMouseClicked

    private void jRadioButtonNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonNamMouseClicked
        if (jRadioButtonNam.isSelected()) {
            jRadioButtonNu.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNamMouseClicked

    private void jRadioButtonNuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonNuMouseClicked
        if (jRadioButtonNu.isSelected()) {
            jRadioButtonNam.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNuMouseClicked

    private void txtTenNguoiThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNguoiThanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNguoiThanActionPerformed

    private void cb_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dayActionPerformed
        String maDay = cb_day.getSelectedItem().toString().trim();

        if (!maDay.equals("Default")) {
            cb_phong.setEnabled(true);
            rooms = controller.getListRoomByIDRange(maDay);
            cb_phong.removeAllItems();

            for (Phong room : rooms) {
                cb_phong.addItem(room.getMaPhong());
            }
        } else {
            cb_phong.setEnabled(false);
        }
    }//GEN-LAST:event_cb_dayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyKTX(user).setVisible(true);
            }
        });
    }

    public static Date addMonths(Date date, int months) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.add(Calendar.MONTH, months);
        return cal.getTime();
    }

    public static Date addDays(Date date, int days) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.add(Calendar.DATE, days); //minus number would decrement the days
        return cal.getTime();
    }

    public boolean checkEmpty(String key, String notify) {
        if (key.trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }

    public boolean checkSoDienThoai(String sdt) {
        String ref = "\\d{10}";
        if (!sdt.trim().matches(ref)) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không đúng định dạng!");
            return false;
        }
        return true;
    }

    public boolean checkExit(String mssv) {
        students = controller.getListStudent();
        
        for (SinhVien student : students) {
            String ms = student.getMSSV().trim();
            if (ms.equals(mssv)) {
                HopDong hd = controller.getHopDongWithId(ms);
                if(checkThoiHan(hd.getNgayDangKy(), hd.getNgayKetThuc())){
                    JOptionPane.showMessageDialog(rootPane, "Sinh viên còn thời hạn đăng kí\n hợp đồng");
                    return false;
                }
            }
        }
        return true;
    }
    boolean checkThoiHan(Date ngayDangKy, Date ngayKetThuc) {

        Date todayDate = java.util.Calendar.getInstance().getTime();
        if (!ngayDangKy.after(todayDate) && !ngayKetThuc.before(todayDate)) {
            return true;
        }
        return false;
    }

    public boolean checkBirthday(String key, String notify) {
        String ref = "^(0?[1-9]|[12][0-9]|3[01])[/](0?[1-9]|1[012])[/]\\d{4}$";
        if (!key.trim().matches(ref)) {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }

    public boolean checkComboBox(String key, String notify) {
        if (key.trim().length() > 0 && key.equals("Default")) {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_dang_ky;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_dang_ki;
    private javax.swing.JLabel btn_help;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_setting2;
    private javax.swing.JLabel btn_user;
    private javax.swing.JComboBox<String> cb_day;
    private javax.swing.JComboBox<String> cb_loai_phong;
    private javax.swing.JComboBox<String> cb_phong;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JLabel setting_view;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiaChiNguoThan;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtHovaTen;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgayThangNamSinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoDienThoaiNguoiThan;
    private javax.swing.JTextField txtTenNguoiThan;
    // End of variables declaration//GEN-END:variables
}
