/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyktx.view.Admin;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import quanlyktx.DAO.DAO;
import quanlyktx.model.Day;
import quanlyktx.model.Phong;
import quanlyktx.model.SinhVien;
import quanlyktx.view.DangNhap.DangNhapView;

/**
 *
 * @author luong
 */
public class QuanLyPhongView extends javax.swing.JFrame {

    public static String user;
    List<Day> ranges;
    List<Phong> rooms;
    DAO controller;
    DefaultTableModel model;

    /**
     * Creates new form QuanLyPhong
     */
    public QuanLyPhongView(String id) {
        this.user = id;
        setIcon();
        initComponents();
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        tbl_quan_ly.setVisible(false);
        ////

        controller = new DAO();
        ranges = controller.getListRange();
        rooms = controller.getListRoom();
        model = (DefaultTableModel) tbl_quan_ly.getModel();

        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Kí túc xá");
        for (Day range : ranges) {
            DefaultMutableTreeNode dayNode = new DefaultMutableTreeNode(range.getTenDay());
            rootNode.add(dayNode);
            for (Phong room : rooms) {
                //System.out.println(room.getMaDay().trim() + "_" + range.getMaDay().trim());
                if (room.getMaDay().trim().equals(range.getMaDay().trim())) {
                    DefaultMutableTreeNode phongNode = new DefaultMutableTreeNode(room.getMaPhong());
                    dayNode.add(phongNode);
                }
            }
            DefaultTreeModel defaultTreeModel = new DefaultTreeModel(dayNode);
            treeRoom.setModel(defaultTreeModel);
        }
        DefaultTreeModel defaultTreeModel = new DefaultTreeModel(rootNode);
        treeRoom.setModel(defaultTreeModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logout = new javax.swing.JLabel();
        btn_help = new javax.swing.JLabel();
        btn_user = new javax.swing.JLabel();
        setting_view = new javax.swing.JLabel();
        btn_setting = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeRoom = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_quan_ly = new javax.swing.JTable();
        btn_sua = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JLabel();
        btn_them = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 190, 55));

        btn_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_helpMouseClicked(evt);
            }
        });
        getContentPane().add(btn_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, 55));

        btn_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
        });
        getContentPane().add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, 190, 55));

        setting_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/setting.jpg"))); // NOI18N
        getContentPane().add(setting_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 220));

        btn_setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_settingMouseClicked(evt);
            }
        });
        getContentPane().add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 192, 50));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 25, 20));

        treeRoom.setBackground(new java.awt.Color(255, 255, 204));
        treeRoom.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý"));
        treeRoom.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        treeRoom.setForeground(new java.awt.Color(255, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Kí túc xá");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Dãy");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nam");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("I");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng I10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("J");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng J10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("H");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng H10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Q");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Q10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nữ");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("M");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng M10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("N");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng N10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("K");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng K10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("P");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P01");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P02");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P03");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P04");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P05");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P06");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P07");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P08");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P09");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Phòng P10");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeRoom.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        treeRoom.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeRoomValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeRoom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 210, 410));

        tbl_quan_ly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_quan_ly.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_quan_ly.setOpaque(false);
        jScrollPane2.setViewportView(tbl_quan_ly);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 470, 410));

        btn_sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 498, 110, 40));

        btn_xoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 498, 110, 40));

        btn_them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 498, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/QuanLyPhong.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        this.dispose();
        new AdminView().setVisible(true);
    }//GEN-LAST:event_btn_closeMouseClicked
    private boolean flag = true;
    private void btn_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseClicked
        if (flag) {
            setting_view.setVisible(true);
            btn_user.setVisible(true);
            btn_help.setVisible(true);
            btn_logout.setVisible(true);
            flag = false;
        } else {
            setting_view.setVisible(false);
            btn_user.setVisible(false);
            btn_help.setVisible(false);
            btn_logout.setVisible(false);
            flag = true;
        }
    }//GEN-LAST:event_btn_settingMouseClicked

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click user");
        this.dispose();
        new UserView().setVisible(true);
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_helpMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click help");
        new HelpView().setVisible(true);
    }//GEN-LAST:event_btn_helpMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        setting_view.setVisible(false);
        btn_user.setVisible(false);
        btn_help.setVisible(false);
        btn_logout.setVisible(false);
        flag = true;
        System.out.println("click logout");
        this.dispose();
        new DangNhapView().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void treeRoomValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeRoomValueChanged
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeRoom.getLastSelectedPathComponent();

        String d = (String) selectedNode.getUserObject();
        if (d.trim().length() > 3) {
            model.setColumnCount(0);
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{
                "STT", "Mã phòng", "Mã dãy", "Tối thiểu", "Tối đa", "Mã loại phòng", "Tình trạng"
            });
            List<Phong> temp = new ArrayList<>();
            for (Phong phong : rooms) {
                System.out.println(d.trim() + "_" + ("Dãy " + phong.getMaDay()).trim());
                if (("Dãy " + phong.getMaDay()).trim().equals(d.trim())) {
                    temp.add(phong);
                }
            }

            if (temp.size() > 0) {
                tbl_quan_ly.setVisible(true);
            }

            showDataPhong(temp, model);
        } else if (d.trim().length() == 3) {

            model.setColumnCount(0);
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{
                "STT", "Họ và tên", "Mã SV", "Quê quán", "Ngày đăng kí", "Ngày hết hạn", ""
            });
            controller.showDataDetailPhong(model, d);
        }

    }//GEN-LAST:event_treeRoomValueChanged

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeRoom.getLastSelectedPathComponent();
        if (selectedNode != null) {
            String d = (String) selectedNode.getUserObject();
            System.out.println(d);
            Phong p = controller.getRoom(d);
            if (d == null) {
                JOptionPane.showMessageDialog(rootPane, "Chọn dòng cần thêm!");
            } else {
                ThemPhong edit = new ThemPhong(this, rootPaneCheckingEnabled);
                edit.setVisible(true);

            }
        }
    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeRoom.getLastSelectedPathComponent();

        String d = (String) selectedNode.getUserObject();
        if (d.trim().length() > 3) {
        } else if (d.trim().length() == 3) {
            Phong p = controller.getRoom(d);
            SuaThongTinPhong edit = new SuaThongTinPhong(this, rootPaneCheckingEnabled);
            edit.setEditData(p);
            edit.setVisible(true);

            controller.showDataDetailPhong(model, d);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng cần sửa!");
        }
    }//GEN-LAST:event_btn_suaMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeRoom.getLastSelectedPathComponent();

        if (selectedNode.getUserObject() == null) {
            String d = (String) selectedNode.getUserObject();
            if (d.trim().length() > 3) {
            } else if (d.trim().length() == 3) {
                if (controller.deletePhong(d)) {
                    JOptionPane.showMessageDialog(rootPane, "Xóa phòng thành công!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa phòng thất bại!\n Phòng có liên kết với nhiều dữ liệu khác");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Chọn dòng cần xóa!");
            }
        }
    }//GEN-LAST:event_btn_xoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhongView(user).setVisible(true);
            }
        });
    }

    public void showDataDay(List<Day> data, DefaultTableModel model) {
        int i = 1;
        model.setRowCount(0);
        for (Day d : data) {
            model.addRow(new Object[]{
                i++,
                d.getMaDay().trim(),
                d.getTenDay(),
                d.getGioiTinh(),
                d.getTinhTrang(),});
        }
    }

    public void showDataPhong(List<Phong> data, DefaultTableModel model) {
        int i = 1;
        model.setRowCount(0);
        for (Phong p : data) {
            String tt = p.getTinhTrang() == 1 ? "Đóng" : "Mở";
            model.addRow(new Object[]{
                i++,
                p.getMaPhong(),
                p.getMaDay().trim(),
                p.getToiThieu(),
                p.getToiDa(),
                p.getMaLoaiPhong(),
                tt
            });
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_help;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_setting;
    private javax.swing.JLabel btn_sua;
    private javax.swing.JLabel btn_them;
    private javax.swing.JLabel btn_user;
    private javax.swing.JLabel btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel setting_view;
    private javax.swing.JTable tbl_quan_ly;
    private javax.swing.JTree treeRoom;
    // End of variables declaration//GEN-END:variables

    void updateEdit() {
        treeRoom.removeAll();
        ranges = controller.getListRange();
        rooms = controller.getListRoom();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeRoom.getLastSelectedPathComponent();

        String d = (String) selectedNode.getUserObject();
        if (d.trim().length() > 3) {
            model.setColumnCount(0);
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{
                "STT", "Mã phòng", "Mã dãy", "Tối thiểu", "Tối đa", "Mã loại phòng", "Tình trạng"
            });
            List<Phong> temp = new ArrayList<>();
            for (Phong phong : rooms) {
                System.out.println(d.trim() + "_" + ("Dãy " + phong.getMaDay()).trim());
                if (("Dãy " + phong.getMaDay()).trim().equals(d.trim())) {
                    temp.add(phong);
                }
            }

            if (temp.size() > 0) {
                tbl_quan_ly.setVisible(true);
            }

            showDataPhong(temp, model);
        } else if (d.trim().length() == 3) {

            model.setColumnCount(0);
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{
                "STT", "Họ và tên", "Mã SV", "Quê quán", "Ngày đăng kí", "Ngày hết hạn", ""
            });
            controller.showDataDetailPhong(model, d);
        }
        treeRoom.repaint();
    }
}
