/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyktx.view.Admin;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import quanlyktx.model.SinhVien;

/**
 *
 * @author luong
 */
public class SuaThongTin extends javax.swing.JDialog {

    QuanLySVView home;
    /**
     * Creates new form SuaThongTin
     */
    public SuaThongTin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (QuanLySVView) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMSSV = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        rbtn_nam = new javax.swing.JRadioButton();
        rbtn_nu = new javax.swing.JRadioButton();
        btn_save = new javax.swing.JLabel();
        btn_cancle = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMSSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMSSV.setBorder(null);
        txtMSSV.setEnabled(false);
        txtMSSV.setOpaque(false);
        getContentPane().add(txtMSSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 270, 25));

        txtTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTen.setBorder(null);
        txtTen.setOpaque(false);
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 162, 270, 25));

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNgaySinh.setBorder(null);
        txtNgaySinh.setOpaque(false);
        getContentPane().add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 215, 200, 25));

        txtQueQuan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQueQuan.setBorder(null);
        txtQueQuan.setOpaque(false);
        getContentPane().add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 270, 25));

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDiaChi.setBorder(null);
        txtDiaChi.setOpaque(false);
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 310, 25));

        txtSDT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSDT.setBorder(null);
        txtSDT.setOpaque(false);
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 322, 270, 25));

        rbtn_nam.setBackground(new java.awt.Color(255, 204, 153));
        rbtn_nam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbtn_nam.setText("Nam");
        rbtn_nam.setBorder(null);
        rbtn_nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtn_nam.setOpaque(false);
        rbtn_nam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_namMouseClicked(evt);
            }
        });
        getContentPane().add(rbtn_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 60, -1));

        rbtn_nu.setBackground(new java.awt.Color(255, 204, 153));
        rbtn_nu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbtn_nu.setText("Nữ");
        rbtn_nu.setBorder(null);
        rbtn_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtn_nu.setOpaque(false);
        rbtn_nu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_nuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbtn_nuMouseEntered(evt);
            }
        });
        getContentPane().add(rbtn_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 60, -1));

        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 540, 82, 35));

        btn_cancle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancleMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 542, 73, 33));

        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/close.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/Sua_thong_tin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        setSize(new java.awt.Dimension(500, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancleMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancleMouseClicked

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
       String stringDate = txtNgaySinh.getText();

        try {
            String gioiTinh = rbtn_nam.isSelected() ? "Nam" : "Nữ";
            Date ngaySinh = new SimpleDateFormat("dd/MM/yyyy").parse(stringDate);

            SinhVien sinhVien
                    = new SinhVien(txtMSSV.getText(),
                            txtTen.getText(),
                            ngaySinh,
                            gioiTinh,
                            txtQueQuan.getText(),
                            txtSDT.getText(),
                            txtDiaChi.getText(),
                            txtMSSV.getText());
            home.updateSinhVien(sinhVien);
        } catch (ParseException ex) {
            Logger.getLogger(DangKyKTX.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btn_saveMouseClicked

    private void rbtn_nuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_nuMouseClicked
        
        if (rbtn_nu.isSelected()) {
            rbtn_nam.setSelected(false);
        }
    }//GEN-LAST:event_rbtn_nuMouseClicked

    private void rbtn_namMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_namMouseClicked
        if (rbtn_nam.isSelected()) {
            rbtn_nu.setSelected(false);
        }
    }//GEN-LAST:event_rbtn_namMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void rbtn_nuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_nuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_nuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaThongTin dialog = new SuaThongTin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cancle;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtn_nam;
    private javax.swing.JRadioButton rbtn_nu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    public void setEditData(SinhVien s) {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String ngaySinh = format.format(s.getNgaySinh());
        //System.out.println(s.getGioiTinh().trim());
        txtMSSV.setText(s.getMSSV().trim());
        txtTen.setText(s.getTen().trim());
        txtNgaySinh.setText(ngaySinh.trim());
        txtQueQuan.setText(s.getQueQuan().trim());
        txtSDT.setText(s.getSDT().trim());
        txtDiaChi.setText(s.getDiaChi().trim());
        if(s.getGioiTinh().trim().equals("Nam")) {
            rbtn_nam.setSelected(true);
            rbtn_nu.setSelected(false);
        }else if(s.getGioiTinh().trim().equals("Nữ"))  {
            rbtn_nam.setSelected(false);
            rbtn_nu.setSelected(true);
        }
        
    }
}
