/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyktx.view.Admin;

import java.util.List;
import javax.swing.JOptionPane;
import quanlyktx.DAO.DAO;
import quanlyktx.model.PhatSinh;

/**
 *
 * @author luong
 */
public class ThemPhatSinh extends javax.swing.JDialog {

    /**
     * Creates new form ThemPhatSinh
     */
    ThuPhiView home;
    private DAO controller = new DAO();
    List<PhatSinh> services;

    public ThemPhatSinh(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (ThuPhiView) parent;
        services = controller.getListServices();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_save = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        lb_Ten = new javax.swing.JLabel();
        lb_gia = new javax.swing.JLabel();
        lb_dv_tinh = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        txt_dv_tinh = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 82, 35));

        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 540, 75, 35));

        lb_Ten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_Ten.setText("Tên phát sinh:");
        getContentPane().add(lb_Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lb_gia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_gia.setText("Giá tiền:");
        getContentPane().add(lb_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        lb_dv_tinh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_dv_tinh.setText("Đơn vị tính: ");
        getContentPane().add(lb_dv_tinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txt_gia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 270, -1));

        txt_dv_tinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_dv_tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dv_tinhActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dv_tinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 270, -1));

        txt_ten.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyktx/images/Sua_thong_tin_Phat_sinh.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(500, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        if (checkEmpty(txt_ten.getText(), "Tên phat sinh?")
                && checkEmpty(txt_dv_tinh.getText(), "Đơn vị tính?")
                && checkEmpty(txt_gia.getText(), "Giá phát sinh?")) {
            PhatSinh phatSinh = new PhatSinh();
            int i = services.size() + 1;
            String ma = i > 10 ? "PS" : "PS0";
            phatSinh.setMaPS(ma + i);
            phatSinh.setTenPS(txt_ten.getText().trim());
            phatSinh.setDonViTinh(txt_dv_tinh.getText().trim());
            phatSinh.setGiaTienPS(Integer.parseInt(txt_gia.getText().trim()));

            if (controller.addServices(phatSinh)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm phát sinh thành công.");
                home.showServices();
                this.dispose();
            }

        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void txt_dv_tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dv_tinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dv_tinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemPhatSinh dialog = new ThemPhatSinh(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public boolean checkEmpty(String key, String notify) {
        if (key.trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, notify);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_Ten;
    private javax.swing.JLabel lb_dv_tinh;
    private javax.swing.JLabel lb_gia;
    private javax.swing.JTextField txt_dv_tinh;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables

}
